### ISSUE TITLE
When `from` index is beyond the maximum index, introduces a new undefined element

### ISSUE THREAD

**Issue by mob-dashi** [sindresorhus/array-move#12]
It's not clear to me whether this is desired behavior.  It's certainly not included in the test cases.  For our purposes, it would be better if it left the array unmolested, but at least it should be tested and documented.

```
const a = [1, 2, 3, 4, 5];
console.log(arrayMove(a, 6, 0));
> [undefined, 1, 2, 3, 4, 5]
```

**Comment by sindresorhus** [comment]
I agree. That's definitely not wanted behavior. It could either just leave the array alone or throw an "out of bounds" error. I think just leaving the array alone would be more JavaScript'y.
