### ISSUE TITLE
i think the "startIndex" may be applied to "from"

### ISSUE THREAD

**Issue by cszo** [sindresorhus/array-move#15]
```js
let arr = [1,2,3];

console.log(arrayMove(arr,-1000,0)); // [ undefined, 1, 2, 3 ]
```
when i change this line
```js
const startIndex = from < 0 ? array.length + from : from;
```
the result is
```js
console.log(arrayMove(arr,-1000,0)); // [ 1, 2, 3 ]
```

**Comment by sindresorhus** [comment]
// @Richienb

**Comment by Richienb** [comment]
@cszo I'm not seeing a problem here.

![image](https://user-images.githubusercontent.com/29491356/89460533-8bf3f300-d7be-11ea-81bd-3e91360206cd.png)

Can you provide a unit test illustrating it?

**Comment by cszo** [comment]
sorry..., I was wrong,I want to say `arrayMove(arr,1000,0)` and I expect the result `[ 1, 2, 3 ]` 

![image](https://user-images.githubusercontent.com/25258338/89479904-92866880-d7c6-11ea-8d32-16c68a9231fb.jpeg)
