### ISSUE TITLE
hello,An error occurred while updating the new package

### ISSUE THREAD

**Issue by lichenglong-blog** [sindresorhus/array-move#21]
error: Uncaught (in promise) TypeError: (0 , A.default) is not a function
![image](https://user-images.githubusercontent.com/24689873/129145808-3772a18f-cefd-4340-b38f-2c2986511909.png)
![image](https://user-images.githubusercontent.com/24689873/129145898-cc3af3ba-d80d-49db-a53c-17a3dacbf365.png)
![image](https://user-images.githubusercontent.com/24689873/129145937-d34da740-e732-419b-b92e-d4e5be9360e6.png)
version:latest

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
