### ISSUE TITLE
Not compatible with node 15. 

### ISSUE THREAD

**Issue by hackerghost93** [sindresorhus/array-move#24]
Is there a problem with node 15 to be specific with this library ? 

yarn add v1.22.11
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error array-move@4.0.0: The engine "node" is incompatible with this module. Expected version "^12.20.0 || ^14.13.1 || >=16.0.0". Got "15.14.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

this is what i get when i try to install array move for node 15.

**Comment by sindresorhus** [comment]
Node.js 15 is no longer supported by the Node.js team, so it's not supported here either. I suggest upgrading to Node.js 16.
