### ISSUE TITLE
Incompatible with Jest

### ISSUE THREAD

**Issue by wdfinch** [sindresorhus/array-move#25]
Hi there. First off thanks for making this library! It's really helpful. I'm having an issue when trying to test my code that uses this library via `jest`. I believe the issue that is that jest does not have full support yet for ESM. Therefore during my test, I'm getting:

`SyntaxError: Unexpected token 'export'`

Would it be possible to export a Common JS version of the library as well as an ESM version? Rollup can do this automatically.

https://jestjs.io/docs/ecmascript-modules

**Comment by sindresorhus** [comment]
I have no plans to bring back CommonJS support.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#im-having-problems-with-esm-and-jest

**Comment by wdfinch** [comment]
Ok, I'll just rewrite the function myself. I obviously prefer ESM but I can't do anything about jest being incompatable. Thanks for the reply.

**Comment by alexander-schranz** [comment]
In [sulu](https://github.com/sulu/sulu) we got the same problem with `jest` but we did just run it through babel package now like we are doing it for `lodash-es`.

Our my `package.json`:

```json
{
    "jest": {
        "transformIgnorePatterns": [
            "node_modules/(?!(array-move)/)"
        ]
    }
}
```

and in my `webpack.config.js`:

```js
{
    module: {
         rules: [
           {
              test: /\.js$/,
              exclude: /node_modules[/\\](?!(array-move)[/\\])/,
              // ...
           }
       ]
   }
}
```

If you already have other packages here just add `|array-move` to the regex. Pull request as reference: https://github.com/sulu/sulu/pull/6352

**Comment by wdfinch** [comment]
Thanks for the tip! I will try this out.

**Comment by oleksandr-danylchenko** [comment]
Thanks, @alexander-schranz! It helped
