### ISSUE TITLE
Invalid package name "__ngcc_entry_points__.json": name cannot start with an underscore

### ISSUE THREAD

**Issue by MTSebastianAguirre** [sindresorhus/array-move#26]
When I try to install the library, npm give me this error, someone could tell me how to fix it?
![Captura de pantalla 2021-11-26 082720](https://user-images.githubusercontent.com/91618673/143588076-b03554a2-3006-407e-ac51-ab42d4a98b06.png)

**Comment by sindresorhus** [comment]
This has nothing to do with this package. Try to google the error message.
