### ISSUE TITLE
Default export to allow for ease of update

### ISSUE THREAD

**Issue by mytchdot** [sindresorhus/array-move#27]
Quite a small and trivial idea, however, I was wondering why we wouldn't default export the original mutable function. 

While it's an easy thing to change when updating from, say, `2.x -> 4.x`, it seems worth it to simply default export the mutated array function, as that was the behavior prior to pure ESM changes, and that would alleviate the breaking change.

**Comment by sindresorhus** [comment]
With the switch to ESM I'm taking advantage of many years of API learnings to improve the APIs in my projects. Named export is the correct solution here as there are 2 main APIs. Neither are more correct to be the main export.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#when-should-i-use-a-default-export-or-named-exports
