### ISSUE TITLE
Node 18 SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by gunyakov** [sindresorhus/array-move#30]
Try to import this module to node project. Got this error

`SyntaxError: Cannot use import statement outside a module`

if i use require 
`const {arrayMoveImmutable} = require('array-move');`

i got another error 
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/goodzon/Projects/maptorium/node_modules/array-move/index.js from /home/goodzon/Projects/maptorium/routes/job.js not supported.
Instead change the require of index.js in /home/goodzon/Projects/maptorium/routes/job.js to a dynamic import() which is available in all CommonJS modules.
```

if i make 
`const {arrayMoveImmutable} = import('array-move');`
i got 
`TypeError: arrayMoveImmutable is not a function`

How properly make import of module to project???

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
