### ISSUE TITLE
No "main" variable set in package.json

### ISSUE THREAD

**Issue by brownieboy** [sindresorhus/array-move#4]
The package has no "main" set in its package.json file.  This causes systemjs to try and load up the package's entire folder instead of its index.js file!

It needs to be set to:

```
"main": "index.js",
```

**Comment by sindresorhus** [comment]
`"main"` is optional. You can use the `index.js` file convention instead, which I prefer. This is a systemjs bug and should be reported there instead.

See: https://nodejs.org/api/modules.html

**Comment by brownieboy** [comment]
@sindresorhus,

The document that you've referenced does not say that `"main"` is optional.  Nor does it say that Node will look for index.js if `"main"` is missing.

Here's what it _does_ say:

> If there is no package.json file present in the directory, then Node.js will attempt to load an index.js or index.node file out of that directory

And that's not the same thing.

**Comment by sindresorhus** [comment]
It does:

> 1. If X/index.js is a file, load X/index.js as JavaScript text.  STOP

**Comment by SamVerschueren** [comment]
Just wanted to add that I use [camelcase](https://github.com/sindresorhus/camelcase) and [dot-prop](https://github.com/sindresorhus/dot-prop) and they work perfectly fine in SystemJS.
