### ISSUE TITLE
Support browser

### ISSUE THREAD

**Issue by rhys-vdw** [sindresorhus/array-move#7]
Currently this library requires Node.js 8. Please add legacy JS support (just broke our build updating a 10-line library).

**Comment by rhys-vdw** [comment]
Simple as using `function foo()` instead of `const foo = () =>`

**Comment by sindresorhus** [comment]
Just stay on the old version. There's nothing new functionality-wise.

---

This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by rhys-vdw** [comment]
Thanks for the response @sindresorhus. Unfortunately transpiling our dependencies is too much build overhead for our project. We'll probably just maintain a fork.
