### ISSUE TITLE
Leaking ES6 code to ES5 bundle

### ISSUE THREAD

**Issue by dubbha** [sindresorhus/array-move#8]
array-move is leaking ES6 code to ES5 bundle, which later fails on a strict ES5 check with the following error:

```
SyntaxError: The keyword 'const' is reserved (2:590396)
```

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
